/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFuelRecordsRouteImport } from './routes/_authenticated/fuel-records'
import { Route as AuthenticatedNoteCategoriesRouteImport } from './routes/_authenticated/note-categories'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFuelRecordsRoute =
  AuthenticatedFuelRecordsRouteImport.update({
    id: '/fuel-records',
    path: '/fuel-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoteCategoriesRoute =
  AuthenticatedNoteCategoriesRouteImport.update({
    id: '/note-categories',
    path: '/note-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/fuel-records': typeof AuthenticatedFuelRecordsRoute
  '/note-categories': typeof AuthenticatedNoteCategoriesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/fuel-records': typeof AuthenticatedFuelRecordsRoute
  '/note-categories': typeof AuthenticatedNoteCategoriesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fuel-records': typeof AuthenticatedFuelRecordsRoute
  '/_authenticated/note-categories': typeof AuthenticatedNoteCategoriesRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fuel-records'
    | '/note-categories'
    | '/notes'
    | '/tasks'
    | '/trash'
    | '/users'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/fuel-records'
    | '/note-categories'
    | '/notes'
    | '/tasks'
    | '/trash'
    | '/users'
    | '/vehicles'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fuel-records'
    | '/_authenticated/note-categories'
    | '/_authenticated/notes'
    | '/_authenticated/tasks'
    | '/_authenticated/trash'
    | '/_authenticated/users'
    | '/_authenticated/vehicles'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fuel-records': {
      id: '/_authenticated/fuel-records'
      path: '/fuel-records'
      fullPath: '/fuel-records'
      preLoaderRoute: typeof AuthenticatedFuelRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/note-categories': {
      id: '/_authenticated/note-categories'
      path: '/note-categories'
      fullPath: '/note-categories'
      preLoaderRoute: typeof AuthenticatedNoteCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFuelRecordsRoute: typeof AuthenticatedFuelRecordsRoute
  AuthenticatedNoteCategoriesRoute: typeof AuthenticatedNoteCategoriesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFuelRecordsRoute: AuthenticatedFuelRecordsRoute,
  AuthenticatedNoteCategoriesRoute: AuthenticatedNoteCategoriesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
